Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.ssh.insert_key = false
  #config.vm.synced_folder "~/.ssh/id_*", "/home/vagrant/.ssh/"
  config.vm.synced_folder "~/Documents/BEP", "/home/vagrant/BEP"
  config.vm.provision "file",
        source: "~/.ssh/id_rsa",
        destination: "/home/vagrant/.ssh/"
  config.vm.provision "file",
        source: ".bashrc",
        destination: "/home/vagrant/.bashrc"

  config.vm.provider :virtualbox do |virtualbox, override|
    virtualbox.memory = 1024
    override.vm.box_download_checksum_type = "sha256"
    override.vm.box_download_checksum = "b24c912b136d2aa9b7b94fc2689b2001c8d04280cf25983123e45b6a52693fb3"
    override.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1803_01.VirtualBox.box"
  end
end